# Generated by Django 4.0.3 on 2022-03-24 17:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900)),
                ('slug', models.SlugField(max_length=5)),
                ('note', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_list_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Lists',
                'ordering': ['name', 'assigned_to', 'date'],
                'unique_together': {('assigned_to', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=900)),
                ('slug', models.SlugField(max_length=5)),
                ('note', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(choices=[('I', '1'), ('II', '2'), ('III', '3'), ('IV', '4'), ('V', '5'), ('VI', '6'), ('VII', '7'), ('VIII', '8'), ('IX', '9'), ('X', '10')])),
                ('status', models.CharField(choices=[('XXXX', 'TODO'), ('XXX', 'IN PROGRESS'), ('XX', 'PAUSE'), ('X', 'DONE')], max_length=15)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('due_date', models.DateField(blank=True, default=datetime.datetime(2022, 4, 8, 18, 47, 5, 292731), null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, default=datetime.datetime(2022, 4, 8, 18, 47, 5, 292910), null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_task_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_created_by', to=settings.AUTH_USER_MODEL)),
                ('task_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.list')),
            ],
            options={
                'ordering': ['task_list', 'title', 'due_date', 'priority', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('file', models.FileField(max_length=855, upload_to='media/')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.task')),
            ],
            options={
                'ordering': ['task', 'timestamp'],
            },
        ),
    ]
