# Generated by Django 4.0.3 on 2022-03-25 10:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_alter_task_completed_date_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 9, 11, 13, 48, 64523), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 9, 11, 13, 48, 64363), null=True),
        ),
    ]
