# Generated by Django 4.0.3 on 2022-03-20 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_list_assigned_to_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 4, 15, 35, 7, 44597), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 4, 15, 35, 7, 44433), null=True),
        ),
    ]
