# Generated by Django 4.0.3 on 2022-03-20 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_author_list_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 4, 20, 36, 42, 297411), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 4, 20, 36, 42, 297233), null=True),
        ),
    ]
