# Generated by Django 4.0.3 on 2022-03-21 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_task_completed_date_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 5, 19, 44, 59, 719821), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 5, 19, 44, 59, 719663), null=True),
        ),
    ]
