# Generated by Django 4.0.3 on 2022-03-26 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_filename_attachment_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file_name',
            new_name='filetitle',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 10, 20, 3, 11, 263914), null=True),
        ),
    ]
