# Generated by Django 4.0.3 on 2022-03-26 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_file_name_attachment_filetitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='filetitle',
            new_name='file_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 10, 20, 8, 0, 522961), null=True),
        ),
    ]
