# Generated by Django 4.0.3 on 2022-03-26 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_filetitle_attachment_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 10, 20, 13, 33, 657213), null=True),
        ),
    ]
