# Generated by Django 4.0.3 on 2022-03-31 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 15, 13, 41, 4, 493888), null=True),
        ),
    ]
